<?php

namespace Sm\TaskBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
    /**
     * Get pagination query
     *
     * @return \Doctrine\ORM\Query
     */
    public function getPaginationQuery()
    {
        $dql   = "SELECT task, priority FROM SmTaskBundle:Task task JOIN task.priority priority";
        return $this->_em->createQuery($dql);
    }
}
