Sm\TaskBundle\Entity\Priority:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            type: integer
            groups: [priority]
        name:
            expose: true
            type: string
            groups: [priority]
